#ifndef X11_XATOM_H
#define X11_XATOM_H

#define XA_PRIMARY             1
#define XA_SECONDARY           2
#define XA_ARC                 3
#define XA_ATOM                4
#define XA_BITMAP              5
#define XA_CARDINAL            6
#define XA_COLORMAP            7
#define XA_CURSOR              8
#define XA_CUT_BUFFER0         9
#define XA_CUT_BUFFER1         10
#define XA_CUT_BUFFER2         11
#define XA_CUT_BUFFER3         12
#define XA_CUT_BUFFER4         13
#define XA_CUT_BUFFER5         14
#define XA_CUT_BUFFER6         15
#define XA_CUT_BUFFER7         16
#define XA_DRAWABLE            17
#define XA_FONT                18
#define XA_INTEGER             19
#define XA_PIXMAP              20
#define XA_POINT               21
#define XA_RECTANGLE           22
#define XA_RESOURCE_MANAGER    23
#define XA_RGB_COLOR_MAP       24
#define XA_RGB_BEST_MAP        25
#define XA_RGB_BLUE_MAP        26
#define XA_RGB_DEFAULT_MAP     27
#define XA_RGB_GRAY_MAP        28
#define XA_RGB_GREEN_MAP       29
#define XA_RGB_RED_MAP         30
#define XA_STRING              31
#define XA_VISUALID            32
#define XA_WINDOW              33
#define XA_WM_COMMAND          34
#define XA_WM_HINTS            35
#define XA_WM_CLIENT_MACHINE   36
#define XA_WM_ICON_NAME        37
#define XA_WM_ICON_SIZE        38
#define XA_WM_NAME             39
#define XA_WM_NORMAL_HINTS     40
#define XA_WM_SIZE_HINTS       41
#define XA_WM_ZOOM_HINTS       42
#define XA_MIN_SPACE           43
#define XA_NORM_SPACE          44
#define XA_MAX_SPACE           45
#define XA_END_SPACE           46
#define XA_SUPERSCRIPT_X       47
#define XA_SUPERSCRIPT_Y       48
#define XA_SUBSCRIPT_X         49
#define XA_SUBSCRIPT_Y         50
#define XA_UNDERLINE_POSITION  51
#define XA_UNDERLINE_THICKNESS 52
#define XA_STRIKEOUT_POSITION  53
#define XA_STRIKEOUT_DESCENT   54
#define XA_ITALIC_ANGLE        55
#define XA_X_HEIGHT            56
#define XA_QUAD_WIDTH          57
#define XA_WEIGHT              58
#define XA_POINT_SIZE          59
#define XA_RESOLUTION          60
#define XA_COPYRIGHT           61
#define XA_NOTICE              62
#define XA_FONT_NAME           63
#define XA_FAMILY_NAME         64
#define XA_FULL_NAME           65
#define XA_CAP_HEIGHT          66
#define XA_WM_CLASS            67
#define XA_TRANSIENT_FOR       68

#endif
