name: World

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install pip dependencies
      run: python -m pip install -U setuptools wheel build
    - name: Install build dependencies
      run: cd wow_world_messages && python -m pip install .
    - name: Run tests
      run: cd wow_world_messages && python -m unittest
    - name: Build
      run: python -m build wow_world_messages
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels
        path: wow_world_messages/dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/wow_world_messages-v')"
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: wheels
