#ifndef LIBRENDER_DRAWABLE_BUFFERS_H
# define LIBRENDER_DRAWABLE_BUFFERS_H

# define DRAWABLE_BUFFER_POSITIONS	0x01
# define DRAWABLE_BUFFER_TEX_COORDS	0x02
# define DRAWABLE_BUFFER_COLORS		0x04
# define DRAWABLE_BUFFER_INDICES	0x08

#endif
