NAME    = libpng
VERSION = 1.6.40
TAR     = $(NAME)-$(VERSION).tar.gz
DIR     = $(NAME)-$(VERSION)
URL     = https://github.com/glennrp/libpng/archive/refs/tags/v$(VERSION).tar.gz
HASH    = a00e9d2f2f664186e4202db9299397f851aea71b36a35e74910b8820e380d441

include ../mk/tar.mk
include ../mk/automake.mk
