#include "elf_32.h"

#define ELFEM EM_MIPS_RS3_LE

#define R_NONE         R_MIPS_NONE
#define R_RELATIVE32   R_MIPS_REL_32
#define R_JMP_SLOT32   R_MIPS_JUMP_SLOT
#define R_GLOB_DAT32   R_MIPS_GLOB_DAT
#define R_ABS32        R_MIPS_32
#define R_TLS_DTPMOD32 R_MIPS_TLS_DTPMOD32
#define R_TLS_DTPOFF32 R_MIPS_TLS_DTPREL32
#define R_TLS_TPOFF32  R_MIPS_TLS_TPREL32
