[package]
name = "wow_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace = true
wow_login_messages.workspace = true
wow_srp.workspace = true
