NAME    = libogg
VERSION = 1.3.5
TAR     = $(NAME)-$(VERSION).tar.xz
DIR     = $(NAME)-$(VERSION)
URL     = https://downloads.xiph.org/releases/ogg/$(TAR)
HASH    = c4d91be36fc8e54deae7575241e03f4211eb102afb3fc0775fbbc1b740016705

include ../mk/tar.mk
include ../mk/automake.mk
