NAME    = flac
VERSION = 1.4.3
TAR     = $(NAME)-$(VERSION).tar.xz
DIR     = $(NAME)-$(VERSION)
URL     = https://downloads.xiph.org/releases/flac/$(TAR)
HASH    = 91cfc3ed61dc40f47f050a109b08610667d73477af6ef36dcad31c31a4a8d53f

include ../mk/tar.mk
include ../mk/automake.mk
