#ifndef TITLE_SCREEN_MODE_H
#define TITLE_SCREEN_MODE_H

enum title_screen_mode
{
	TITLE_SCREEN_TITLE,
	TITLE_SCREEN_SINGLEPLAYER,
	TITLE_SCREEN_MULTIPLAYER,
	TITLE_SCREEN_TEXTURE_PACKS,
	TITLE_SCREEN_OPTIONS,
};

#endif
