#ifndef LIBRENDER_SHADER_SPRITE_UPDATE_H
# define LIBRENDER_SHADER_SPRITE_UPDATE_H

# define SHADER_SPRITE_UPDATE_VERTEXES		0x01
# define SHADER_SPRITE_UPDATE_TEX_COORDS	0x02
# define SHADER_SPRITE_UPDATE_COLORS		0x04

#endif
