BIN = libelf

SRC = elf.c \
      elf32.c \
      elf64.c \

HDR = libelf.h \
      libelf32.h \
      libelf64.h \

LIB = libz.so \

VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_BUILD = 0

include $(MAKEDIR)/lib.mk
