NAME    = libvorbis
VERSION = 1.3.7
TAR     = $(NAME)-$(VERSION).tar.xz
DIR     = $(NAME)-$(VERSION)
URL     = https://downloads.xiph.org/releases/vorbis/$(TAR)
HASH    = b33cc4934322bcbf6efcbacf49e3ca01aadbea4114ec9589d1b1e9d20f72954b

include ../mk/tar.mk
include ../mk/automake.mk
