include $(MAKEDIR)/env.mk

DIRS = ld \
       libasm \
       libc \
       libdbg \
       libdl \
       libdwarf \
       libelf \
       libfetch \
       libh261 \
       libhistory \
       libjpeg \
       libm \
       libpng \
       libpthread \
       libreadline \
       libutil \
       libz \

include $(MAKEDIR)/dir.mk
