NAME    = libsamplerate
VERSION = 0.2.2
TAR     = $(NAME)-$(VERSION).tar.xz
DIR     = $(NAME)-$(VERSION)
URL     = https://github.com/libsndfile/libsamplerate/releases/download/$(VERSION)/$(TAR)
HASH    = 3258da280511d24b49d6b08615bbe824d0cacc9842b0e4caf11c52cf2b043893

include ../mk/tar.mk
include ../mk/automake.mk
